package middleware

const (
	ChannelID                   = "channel_id"
	ChannelScope                = "channel_scope"
	Group                       = "group"
	Token                       = "token"
	AvailableSets               = "available_sets"
	AvailableModels             = "available_models"
	GroupChannelAvailableSets   = "group_channel_available_sets"
	GroupChannelAvailableModels = "group_channel_available_models"
	GroupBalance                = "group_balance"
	RequestModel                = "request_model"
	RequestUser                 = "request_user"
	RequestMetadata             = "request_metadata"
	PromptCacheKey              = "prompt_cache_key"
	RequestServiceTier          = "request_service_tier"
	GroupChannelMode            = "group_channel_mode"
	RequestAt                   = "request_at"
	RequestID                   = "request_id"
	ModelCaches                 = "model_caches"
	ModelConfig                 = "model_config"
	Mode                        = "mode"
	JobID                       = "job_id"
	GenerationID                = "generation_id"
	OperationID                 = "operation_id"
	ResponseID                  = "response_id"
	VideoID                     = "video_id"
	FileID                      = "file_id"

	requestBodyNode = "request_body_node"
)
