package mcpregister

import (
	// register embed mcp
	_ "github.com/labring/aiproxy/mcp-servers/12306"
	_ "github.com/labring/aiproxy/mcp-servers/ableton"
	_ "github.com/labring/aiproxy/mcp-servers/aiproxy-openapi"
	_ "github.com/labring/aiproxy/mcp-servers/alipay"
	_ "github.com/labring/aiproxy/mcp-servers/allvoicelab"
	_ "github.com/labring/aiproxy/mcp-servers/amap"
	_ "github.com/labring/aiproxy/mcp-servers/baidu-map"
	_ "github.com/labring/aiproxy/mcp-servers/bingcn"
	_ "github.com/labring/aiproxy/mcp-servers/blender"
	_ "github.com/labring/aiproxy/mcp-servers/browserbase"
	_ "github.com/labring/aiproxy/mcp-servers/cfworker"
	_ "github.com/labring/aiproxy/mcp-servers/elasticsearch"
	_ "github.com/labring/aiproxy/mcp-servers/fetch"
	_ "github.com/labring/aiproxy/mcp-servers/filesystem"
	_ "github.com/labring/aiproxy/mcp-servers/firecrawl"
	_ "github.com/labring/aiproxy/mcp-servers/flomo"
	_ "github.com/labring/aiproxy/mcp-servers/gezhe"
	_ "github.com/labring/aiproxy/mcp-servers/git"
	_ "github.com/labring/aiproxy/mcp-servers/gpt-vis"
	_ "github.com/labring/aiproxy/mcp-servers/hefeng-weather"
	_ "github.com/labring/aiproxy/mcp-servers/howtocook"
	_ "github.com/labring/aiproxy/mcp-servers/jina-tools"
	_ "github.com/labring/aiproxy/mcp-servers/magic"
	_ "github.com/labring/aiproxy/mcp-servers/oceanbase"
	_ "github.com/labring/aiproxy/mcp-servers/openmemory"
	_ "github.com/labring/aiproxy/mcp-servers/redis"
	_ "github.com/labring/aiproxy/mcp-servers/tavily"
	_ "github.com/labring/aiproxy/mcp-servers/time"
	_ "github.com/labring/aiproxy/mcp-servers/unionpay"
	_ "github.com/labring/aiproxy/mcp-servers/web-search"
	_ "github.com/labring/aiproxy/mcp-servers/xiyan"
	_ "github.com/labring/aiproxy/mcp-servers/zhipuai"
)
